version: "3"
services:
  app:
    container_name: flask_app
    build: ./Backend
    ports:
      - "5000:5000"
    # volumes:
    #   - ./app:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=DockerAppDB
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"